// fetch item list
export const FETCH_ITEM_LIST = 'FETCH_ITEM_LIST';
export const FETCH_ITEM_LIST_SUCCESS = 'FETCH_ITEM_LIST_SUCCESS';
export const FETCH_ITEM_LIST_FAILURE = 'FETCH_ITEM_LIST_FAILURE';
// fetch item details
export const FETCH_ITEM_DETAILS = 'FETCH_ITEM_DETAILS';
export const FETCH_ITEM_DETAILS_SUCCESS = 'FETCH_ITEM_DETAILS_SUCCESS';
export const FETCH_ITEM_DETAILS_FAILURE = 'FETCH_ITEM_DETAILS_FAILURE';